a=int(input("enter total no of 10 rupees:"))
b=int(input("enter total no of 5 rupees:"))
c=int(input("enter total no of 2 rupees:"))
d=int(input("enter total no of 1 rupee:"))
ten=(10*a)
five=(5*b)
two=(2*c)
one=(1*d)
print("the total amount in the piggy bank is",ten+five+two+one)
